<?xml version="1.0"?>
<package format="3">
  <name>robot_rbvogui_forklift</name>
  <version>1.0.0</version>
  <description>
    Forklift robot description, launch files, and deployment configuration for the RB-VOGUI robot
    family
  </description>
  <maintainer email="juan.rascon@eurecat.org">Juan Francisco Rascon Crespo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ground_vehicle_kinematics</exec_depend>
  <exec_depend>joint_position_controller_server</exec_depend>
  <exec_depend>robot_rbvogui_common</exec_depend>
  <exec_depend>robotics_description</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2_launch_helpers</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_tools</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>
  <test_depend>ament_cmake_pep257</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_index_python</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>liburdfdom-tools</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
