# Default xacro arguments for the RB-VOGUI forklift model.
# Runtime arguments such as namespace, robot_name, and sim_file are provided by launch files.

###################################################################################################
# Body
###################################################################################################

body_color: "0.5 0.5 0.5 1.0"
body_use_visual: true
body_use_collision: true
body_use_inertial: true
###################################################################################################
# Steerable wheels
###################################################################################################

s_wheel_use_visual: true
s_wheel_use_v_mesh: true
s_wheel_color: "0.1 0.1 0.1 1.0"
s_wheel_use_inertial: true
s_wheel_steering_joint_limits: "-3.1416 3.1416 100.0 100000.0"
s_wheel_rotation_joint_limits: "100.0 100000.0"

###################################################################################################
# Fork mockup
###################################################################################################

fork_limits: "-0.005 0.2 0.04 20000.0"
fork_dynamics: "10.0 1.0"

###################################################################################################
# Rear top lidar
###################################################################################################

back_top_lidar_use_visual: true
back_top_lidar_use_collision: true
back_top_lidar_use_inertial: true
back_top_lidar_use_v_mesh: true
back_top_lidar_v_mesh_use_low_res: true
back_top_lidar_color: ""
back_top_lidar_use_c_mesh: false
back_top_lidar_c_mesh_use_low_res: true

###################################################################################################
# Front top lidar
###################################################################################################

front_top_lidar_use_visual: true
front_top_lidar_use_collision: true
front_top_lidar_use_inertial: true
front_top_lidar_use_v_mesh: true
front_top_lidar_v_mesh_use_low_res: true
front_top_lidar_color: ""
front_top_lidar_use_c_mesh: false
front_top_lidar_c_mesh_use_low_res: true

###################################################################################################
# Front bottom lidar
###################################################################################################

front_bottom_lidar_use_visual: true
front_bottom_lidar_use_collision: true
front_bottom_lidar_use_inertial: true
front_bottom_lidar_use_v_mesh: true
front_bottom_lidar_v_mesh_use_low_res: true
front_bottom_lidar_color: "1 1 0 1"
front_bottom_lidar_use_c_mesh: false
front_bottom_lidar_c_mesh_use_low_res: true
front_bottom_lidar_ground_clearance: 0.1
